CREATE TABLE item (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode VARCHAR(255) NOT NULL,
    name    VARCHAR(255) NOT NULL,
    price   INTEGER NOT NULL CHECK (price >= 0),
    stock   INTEGER NOT NULL CHECK (stock >= 0),
    CONSTRAINT uk_item_barcode UNIQUE (barcode)
);

CREATE TABLE sale (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date_time   TIMESTAMP,
    total_amount     INTEGER NOT NULL,
    received_amount  INTEGER NOT NULL,
    change_amount    INTEGER NOT NULL
);

CREATE TABLE sale_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id    BIGINT NOT NULL,
    item_id    BIGINT,
    item_name  VARCHAR(255),
    unit_price INTEGER NOT NULL,
    quantity   INTEGER NOT NULL,
    subtotal   INTEGER NOT NULL,
    CONSTRAINT fk_sale_item_sale FOREIGN KEY (sale_id) REFERENCES sale (id)
);
